import { CardItemType } from "../types/CardItemType";

export const DATA: Array<CardItemType> = [{
  id: 1,
  type: 'debit',
  balance: 1000,
  userImage: `https://randomuser.me/api/portraits/women/1.jpg`
}, {
  id: 2,
  type: 'credit',
  balance: 12000,
  userImage: `https://randomuser.me/api/portraits/women/12.jpg`
}, {
  id: 13,
  type: 'debit',
  balance: 1000,
  userImage: `https://randomuser.me/api/portraits/women/13.jpg`
}, {
  id: 14,
  type: 'debit',
  balance: 11000,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 149,
  type: 'debit',
  balance: 110008,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 141,
  type: 'debit',
  balance: 112000,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 2,
  type: 'credit',
  balance: 12000,
  userImage: `https://randomuser.me/api/portraits/women/12.jpg`
}, {
  id: 13,
  type: 'debit',
  balance: 1000,
  userImage: `https://randomuser.me/api/portraits/women/13.jpg`
}, {
  id: 14,
  type: 'debit',
  balance: 11000,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 149,
  type: 'debit',
  balance: 110008,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 141,
  type: 'debit',
  balance: 112000,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 2,
  type: 'credit',
  balance: 12000,
  userImage: `https://randomuser.me/api/portraits/women/12.jpg`
}, {
  id: 13,
  type: 'debit',
  balance: 1000,
  userImage: `https://randomuser.me/api/portraits/women/13.jpg`
}, {
  id: 14,
  type: 'debit',
  balance: 11000,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 149,
  type: 'debit',
  balance: 110008,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 141,
  type: 'debit',
  balance: 112000,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 2,
  type: 'credit',
  balance: 12000,
  userImage: `https://randomuser.me/api/portraits/women/12.jpg`
}, {
  id: 13,
  type: 'debit',
  balance: 1000,
  userImage: `https://randomuser.me/api/portraits/women/13.jpg`
}, {
  id: 14,
  type: 'debit',
  balance: 11000,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 149,
  type: 'debit',
  balance: 110008,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}, {
  id: 141,
  type: 'debit',
  balance: 112000,
  userImage: `https://randomuser.me/api/portraits/women/14.jpg`
}]
